INFO     testApi.py:testApi.py:53 request data：{"grant_type": "password","client_id": "gaodingx","client_secret": "7da458070e57b98e11d00d9286f23537","os": "mac os","mobile_area_code": 86,"mobile": "18218080002","password": "111111"}
DEBUG    urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): fat.gaoding.com:443
DEBUG    urllib3.connectionpool:connectionpool.py:452 https://fat.gaoding.com:443 "POST /connect/oauth/tokens HTTP/1.1" 404 436
INFO     testApi.py:testApi.py:55 response data：{'code': 404, 'body': '<!DOCTYPE html><html>\n            <head><meta charset="UTF-8"/><title>Not Found-404</title></head><body>\n            <h1>Not Found-404</h1><p><pre>NotFoundError: Not Found\n    at Object.throw (/app/node_modules/koa/lib/context.js:97:11)\n    at onError (/app/dist/middlewares/onerror.js:10:22)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:94:5)</pre></p>\n            </body></html>'}